# Notebook 2: Data Cleaning & Preprocessing

**Project:** End-to-End Retail Sales Analytics 
This notebook assumes the Superstore dataset structure and uses the raw dataset from Notebook 1.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("retail_sales_raw_copy.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
print("Shape:", df.shape)
df.info()

Shape: (9994, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [3]:
# Backup copy
df_backup = df.copy()

In [4]:
# Missing values
missing = pd.DataFrame({
    "Missing": df.isnull().sum(),
    "Percent": round(df.isnull().mean()*100,2)
})
missing.sort_values("Percent", ascending=False)

               Missing  Percent
Row ID               0      0.0
Postal Code          0      0.0
Discount             0      0.0
Quantity             0      0.0
Sales                0      0.0
Product Name         0      0.0
Sub-Category         0      0.0
Category             0      0.0
Product ID           0      0.0
Region               0      0.0
State                0      0.0
Order ID             0      0.0
City                 0      0.0
Country              0      0.0
Segment              0      0.0
Customer Name        0      0.0
Customer ID          0      0.0
Ship Mode            0      0.0
Ship Date            0      0.0
Order Date           0      0.0
Profit               0      0.0

In [5]:
# Remove duplicate rows
print("Duplicates before:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicates after:", df.duplicated().sum())

Duplicates before: 0
Duplicates after: 0

In [6]:
# Convert dates
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [7]:
# Standardize text columns
obj_cols = df.select_dtypes(include="object").columns
for col in obj_cols:
    df[col] = df[col].astype(str).str.strip()

In [8]:
# Rename columns (replace spaces with underscores)
df.columns = [c.strip().replace(" ","_") for c in df.columns]
df.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State',
       'Postal_Code', 'Region', 'Product_ID', 'Category', 'Sub-Category',
       'Product_Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [9]:
# Check for negative sales/profit if required
df[["Sales","Profit","Quantity","Discount"]].describe()

              Sales       Profit     Quantity     Discount
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001    28.656896     3.789574     0.156203
std      623.245101   234.260108     2.225110     0.206452
min        0.444000 -6599.978000     1.000000     0.000000
25%       17.280000     1.728750     2.000000     0.000000
50%       54.490000     8.666500     3.000000     0.200000
75%      209.940000    29.364000     5.000000     0.200000
max    22638.480000  8399.976000    14.000000     0.800000

In [10]:
# IQR outlier detection function
def outlier_bounds(series):
    q1=series.quantile(0.25)
    q3=series.quantile(0.75)
    iqr=q3-q1
    return q1-1.5*iqr, q3+1.5*iqr

for col in ["Sales","Profit","Quantity"]:
    low,high=outlier_bounds(df[col])
    print(col, low, high)

Sales -271.71000000000004 498.93
Profit -39.724125 70.816875
Quantity -2.5 9.5

In [11]:
# Feature Engineering
df["Order_Year"] = df["Order_Date"].dt.year
df["Order_Month"] = df["Order_Date"].dt.month
df["Order_Month_Name"] = df["Order_Date"].dt.month_name()
df["Order_Quarter"] = df["Order_Date"].dt.quarter
df["Order_Day"] = df["Order_Date"].dt.day
df["Weekday"] = df["Order_Date"].dt.day_name()
df["Is_Weekend"] = df["Weekday"].isin(["Saturday","Sunday"]).astype(int)

df["Sales_per_Quantity"] = df["Sales"] / df["Quantity"]
df["Profit_Margin"] = (df["Profit"] / df["Sales"]) * 100

df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Order_Year,Order_Month,Order_Month_Name,Order_Quarter,Order_Day,Weekday,Is_Weekend,Sales_per_Quantity,Profit_Margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,4,8,Tuesday,0,130.9800,16.00
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,4,8,Tuesday,0,243.9800,30.00
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,2,12,Sunday,1,7.3100,47.00
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,4,11,Sunday,1,191.5155,-40.00
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,4,11,Sunday,1,11.1840,11.25

In [12]:
# Final checks
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row_ID              9994 non-null   int64
 1   Order_ID            9994 non-null   object
 2   Order_Date          9994 non-null   datetime64[ns]
 3   Ship_Date           9994 non-null   datetime64[ns]
 4   Ship_Mode           9994 non-null   object
 5   Customer_ID         9994 non-null   object
 6   Customer_Name       9994 non-null   object
 7   Segment             9994 non-null   object
 8   Country             9994 non-null   object
 9   City                9994 non-null   object
 10  State               9994 non-null   object
 11  Postal_Code         9994 non-null   int64
 12  Region              9994 non-null   object
 13  Product_ID          9994 non-null   object
 14  Category            9994 non-null   object
 15  Sub-Category        9994 non-null   object
 16  Product_Name        9994 non-null   object
 17  Sales               9994 non-null   float64
 18  Quantity            9994 non-null   int64
 19  Discount            9994 non-null   float64
 20  Profit              9994 non-null   float64
 21  Order_Year          9994 non-null   int32
 22  Order_Month         9994 non-null   int32
 23  Order_Month_Name    9994 non-null   object
 24  Order_Quarter       9994 non-null   int32
 25  Order_Day           9994 non-null   int32
 26  Weekday             9994 non-null   object
 27  Is_Weekend          9994 non-null   int64
 28  Sales_per_Quantity  9994 non-null   float64
 29  Profit_Margin       9994 non-null   float64
dtypes: datetime64[ns](2), float64(5), int32(4), int64(4), object(15)
memory usage: 2.1+ MB
None
Row_ID                0
Order_ID              0
Order_Date            0
Ship_Date             0
Ship_Mode             0
Customer_ID           0
Customer_Name         0
Segment               0
Country               0
City                  0
State                 0
Postal_Code           0
Region                0
Product_ID            0
Category              0
Sub-Category          0
Product_Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Order_Year            0
Order_Month           0
Order_Month_Name      0
Order_Quarter         0
Order_Day             0
Weekday               0
Is_Weekend            0
Sales_per_Quantity    0
Profit_Margin         0
dtype: int64

In [14]:
# Save cleaned dataset
df.to_csv("cleaned_retail_sales.csv", index=False)
print("Saved: data/cleaned_retail_sales.csv")

Saved: data/cleaned_retail_sales.csv