# Notebook 4: Feature Engineering

End-to-End Retail Sales Analytics

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

pd.set_option("display.max_columns", None)

df = pd.read_csv("D:\project_sales\project_for_DA/cleaned_retail_sales.csv", parse_dates=["Order_Date","Ship_Date"])
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Order_Year,Order_Month,Order_Month_Name,Order_Quarter,Order_Day,Weekday,Is_Weekend,Sales_per_Quantity,Profit_Margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,4,8,Tuesday,0,130.9800,16.00
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,4,8,Tuesday,0,243.9800,30.00
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,2,12,Sunday,1,7.3100,47.00
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,4,11,Sunday,1,191.5155,-40.00
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,4,11,Sunday,1,11.1840,11.25

In [2]:
print(df.shape)
df.info()

(9994, 30)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row_ID              9994 non-null   int64
 1   Order_ID            9994 non-null   object
 2   Order_Date          9994 non-null   datetime64[ns]
 3   Ship_Date           9994 non-null   datetime64[ns]
 4   Ship_Mode           9994 non-null   object
 5   Customer_ID         9994 non-null   object
 6   Customer_Name       9994 non-null   object
 7   Segment             9994 non-null   object
 8   Country             9994 non-null   object
 9   City                9994 non-null   object
 10  State               9994 non-null   object
 11  Postal_Code         9994 non-null   int64
 12  Region              9994 non-null   object
 13  Product_ID          9994 non-null   object
 14  Category            9994 non-null   object
 15  Sub-Category        9994 non-null   object
 16  Product_Name        9994 non-null   object
 17  Sales               9994 non-null   float64
 18  Quantity            9994 non-null   int64
 19  Discount            9994 non-null   float64
 20  Profit              9994 non-null   float64
 21  Order_Year          9994 non-null   int64
 22  Order_Month         9994 non-null   int64
 23  Order_Month_Name    9994 non-null   object
 24  Order_Quarter       9994 non-null   int64
 25  Order_Day           9994 non-null   int64
 26  Weekday             9994 non-null   object
 27  Is_Weekend          9994 non-null   int64
 28  Sales_per_Quantity  9994 non-null   float64
 29  Profit_Margin       9994 non-null   float64
dtypes: datetime64[ns](2), float64(5), int64(8), object(15)
memory usage: 2.3+ MB

In [3]:
df["Order_Year"] = df["Order_Date"].dt.year
df["Order_Month"] = df["Order_Date"].dt.month
df["Order_Quarter"] = df["Order_Date"].dt.quarter
df["Order_Day"] = df["Order_Date"].dt.day
df["Order_Week"] = df["Order_Date"].dt.isocalendar().week.astype(int)
df["Day_of_Week"] = df["Order_Date"].dt.day_name()
df["Is_Weekend"] = df["Day_of_Week"].isin(["Saturday","Sunday"]).astype(int)
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Order_Year,Order_Month,Order_Month_Name,Order_Quarter,Order_Day,Weekday,Is_Weekend,Sales_per_Quantity,Profit_Margin,Order_Week,Day_of_Week
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,4,8,Tuesday,0,130.9800,16.00,45,Tuesday
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,4,8,Tuesday,0,243.9800,30.00,45,Tuesday
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,2,12,Sunday,1,7.3100,47.00,23,Sunday
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,4,11,Sunday,1,191.5155,-40.00,41,Sunday
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,4,11,Sunday,1,11.1840,11.25,41,Sunday

In [4]:
df["Shipping_Days"]=(df["Ship_Date"]-df["Order_Date"]).dt.days
df["Sales_per_Quantity"]=df["Sales"]/df["Quantity"]
df["Profit_Margin"]=np.where(df["Sales"]>0,(df["Profit"]/df["Sales"])*100,0)
df["Discount_Flag"]=(df["Discount"]>0).astype(int)
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Order_Year,Order_Month,Order_Month_Name,Order_Quarter,Order_Day,Weekday,Is_Weekend,Sales_per_Quantity,Profit_Margin,Order_Week,Day_of_Week,Shipping_Days,Discount_Flag
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,4,8,Tuesday,0,130.9800,16.00,45,Tuesday,3,0
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,4,8,Tuesday,0,243.9800,30.00,45,Tuesday,3,0
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,2,12,Sunday,1,7.3100,47.00,23,Sunday,4,0
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,4,11,Sunday,1,191.5155,-40.00,41,Sunday,7,1
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,4,11,Sunday,1,11.1840,11.25,41,Sunday,7,1

In [5]:
df["Customer_Order_Count"]=df.groupby("Customer_ID")["Order_ID"].transform("count")
df["Product_Order_Count"]=df.groupby("Product_Name")["Order_ID"].transform("count")
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Order_Year,Order_Month,Order_Month_Name,Order_Quarter,Order_Day,Weekday,Is_Weekend,Sales_per_Quantity,Profit_Margin,Order_Week,Day_of_Week,Shipping_Days,Discount_Flag,Customer_Order_Count,Product_Order_Count
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,4,8,Tuesday,0,130.9800,16.00,45,Tuesday,3,0,5,4
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,4,8,Tuesday,0,243.9800,30.00,45,Tuesday,3,0,5,12
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,2,12,Sunday,1,7.3100,47.00,23,Sunday,4,0,9,7
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,4,11,Sunday,1,191.5155,-40.00,41,Sunday,7,1,15,8
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,4,11,Sunday,1,11.1840,11.25,41,Sunday,7,1,15,5

In [6]:
cols=["Category","Sub_Category","Region","Segment","Ship_Mode","State","City"]
encoders={}
for col in cols:
    if col in df.columns:
        le=LabelEncoder()
        df[col]=le.fit_transform(df[col].astype(str))
        encoders[col]=le
print("Categorical encoding completed.")

Categorical encoding completed.

In [7]:
print(df.isnull().sum())
print(df.columns.tolist())

Row_ID                  0
Order_ID                0
Order_Date              0
Ship_Date               0
Ship_Mode               0
Customer_ID             0
Customer_Name           0
Segment                 0
Country                 0
City                    0
State                   0
Postal_Code             0
Region                  0
Product_ID              0
Category                0
Sub-Category            0
Product_Name            0
Sales                   0
Quantity                0
Discount                0
Profit                  0
Order_Year              0
Order_Month             0
Order_Month_Name        0
Order_Quarter           0
Order_Day               0
Weekday                 0
Is_Weekend              0
Sales_per_Quantity      0
Profit_Margin           0
Order_Week              0
Day_of_Week             0
Shipping_Days           0
Discount_Flag           0
Customer_Order_Count    0
Product_Order_Count     0
dtype: int64
['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode', 'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State', 'Postal_Code', 'Region', 'Product_ID', 'Category', 'Sub-Category', 'Product_Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Order_Year', 'Order_Month', 'Order_Month_Name', 'Order_Quarter', 'Order_Day', 'Weekday', 'Is_Weekend', 'Sales_per_Quantity', 'Profit_Margin', 'Order_Week', 'Day_of_Week', 'Shipping_Days', 'Discount_Flag', 'Customer_Order_Count', 'Product_Order_Count']

In [10]:
df.to_csv("D:\project_sales\project_for_DA/feature_engineered_retail_sale.csv",index=False)
print("Saved feature_engineered_retail_sales.csv")

Saved feature_engineered_retail_sales.csv